package com.osi.urm.domain;

// Generated Nov 28, 2016 7:51:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiFunctions generated by hbm2java
 */
@Entity
@Table(name = "osi_functions")
public class OsiFunctions implements java.io.Serializable {

	private int id;
	private String funcType;
	private String funcValue;
	private String parameters;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Set<OsiUserFuncExcl> osiUserFuncExcls = new HashSet<OsiUserFuncExcl>(
			0);
	private Set<OsiMenuEntries> osiMenuEntrieses = new HashSet<OsiMenuEntries>(
			0);
	private Set<OsiUserOperationExcl> osiUserOperationExcls = new HashSet<OsiUserOperationExcl>(
			0);

	public OsiFunctions() {
	}

	public OsiFunctions(int id, String funcType, String funcValue) {
		this.id = id;
		this.funcType = funcType;
		this.funcValue = funcValue;
	}

	public OsiFunctions(int id, String funcType, String funcValue,
			String parameters, Integer createdBy, Date createdDate,
			Integer updatedBy, Date updatedDate,
			Set<OsiUserFuncExcl> osiUserFuncExcls,
			Set<OsiMenuEntries> osiMenuEntrieses,
			Set<OsiUserOperationExcl> osiUserOperationExcls) {
		this.id = id;
		this.funcType = funcType;
		this.funcValue = funcValue;
		this.parameters = parameters;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.osiUserFuncExcls = osiUserFuncExcls;
		this.osiMenuEntrieses = osiMenuEntrieses;
		this.osiUserOperationExcls = osiUserOperationExcls;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "func_type", nullable = false, length = 1000)
	public String getFuncType() {
		return this.funcType;
	}

	public void setFuncType(String funcType) {
		this.funcType = funcType;
	}

	@Column(name = "func_value", nullable = false, length = 65535)
	public String getFuncValue() {
		return this.funcValue;
	}

	public void setFuncValue(String funcValue) {
		this.funcValue = funcValue;
	}

	@Column(name = "parameters", length = 65535)
	public String getParameters() {
		return this.parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiFunctions")
	public Set<OsiUserFuncExcl> getOsiUserFuncExcls() {
		return this.osiUserFuncExcls;
	}

	public void setOsiUserFuncExcls(Set<OsiUserFuncExcl> osiUserFuncExcls) {
		this.osiUserFuncExcls = osiUserFuncExcls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiFunctions")
	public Set<OsiMenuEntries> getOsiMenuEntrieses() {
		return this.osiMenuEntrieses;
	}

	public void setOsiMenuEntrieses(Set<OsiMenuEntries> osiMenuEntrieses) {
		this.osiMenuEntrieses = osiMenuEntrieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiFunctions")
	public Set<OsiUserOperationExcl> getOsiUserOperationExcls() {
		return this.osiUserOperationExcls;
	}

	public void setOsiUserOperationExcls(
			Set<OsiUserOperationExcl> osiUserOperationExcls) {
		this.osiUserOperationExcls = osiUserOperationExcls;
	}

}
