package com.osi.urm.domain;

// Generated Nov 28, 2016 7:51:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiMenuEntries generated by hbm2java
 */
@Entity
@Table(name = "osi_menu_entries")
public class OsiMenuEntries implements java.io.Serializable {

	private int id;
	private OsiFunctions osiFunctions;
	private OsiMenus osiMenusBySubMenuId;
	private OsiMenus osiMenusByMenuId;
	private int seq;
	private String menuPrompt;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;

	public OsiMenuEntries() {
	}

	public OsiMenuEntries(int id, OsiMenus osiMenusByMenuId, int seq,
			String menuPrompt) {
		this.id = id;
		this.osiMenusByMenuId = osiMenusByMenuId;
		this.seq = seq;
		this.menuPrompt = menuPrompt;
	}

	public OsiMenuEntries(int id, OsiFunctions osiFunctions,
			OsiMenus osiMenusBySubMenuId, OsiMenus osiMenusByMenuId, int seq,
			String menuPrompt, Integer createdBy, Date createdDate,
			Integer updatedBy, Date updatedDate) {
		this.id = id;
		this.osiFunctions = osiFunctions;
		this.osiMenusBySubMenuId = osiMenusBySubMenuId;
		this.osiMenusByMenuId = osiMenusByMenuId;
		this.seq = seq;
		this.menuPrompt = menuPrompt;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "func_id")
	public OsiFunctions getOsiFunctions() {
		return this.osiFunctions;
	}

	public void setOsiFunctions(OsiFunctions osiFunctions) {
		this.osiFunctions = osiFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_menu_id")
	public OsiMenus getOsiMenusBySubMenuId() {
		return this.osiMenusBySubMenuId;
	}

	public void setOsiMenusBySubMenuId(OsiMenus osiMenusBySubMenuId) {
		this.osiMenusBySubMenuId = osiMenusBySubMenuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public OsiMenus getOsiMenusByMenuId() {
		return this.osiMenusByMenuId;
	}

	public void setOsiMenusByMenuId(OsiMenus osiMenusByMenuId) {
		this.osiMenusByMenuId = osiMenusByMenuId;
	}

	@Column(name = "seq", nullable = false)
	public int getSeq() {
		return this.seq;
	}

	public void setSeq(int seq) {
		this.seq = seq;
	}

	@Column(name = "menu_prompt", nullable = false, length = 100)
	public String getMenuPrompt() {
		return this.menuPrompt;
	}

	public void setMenuPrompt(String menuPrompt) {
		this.menuPrompt = menuPrompt;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
