package com.osi.urm.domain;

// Generated Dec 1, 2016 5:20:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiMenuEntries generated by hbm2java
 */
@Entity
@Table(name = "osi_menu_entries")
public class OsiMenuEntries implements java.io.Serializable {

	private Long id;
	private OsiFunctions osiFunctions;
	private OsiMenus osiMenusBySubMenuId;
	private OsiMenus osiMenusByMenuId;
	private Long seq;
	private String prompt;
	private Date startDate;
	private Date endDate;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;

	public OsiMenuEntries() {
	}

	public OsiMenuEntries(Long id, OsiMenus osiMenusByMenuId, Long seq,
			String prompt, Date startDate, Date endDate) {
		this.id = id;
		this.osiMenusByMenuId = osiMenusByMenuId;
		this.seq = seq;
		this.prompt = prompt;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public OsiMenuEntries(Long id, OsiFunctions osiFunctions,
			OsiMenus osiMenusBySubMenuId, OsiMenus osiMenusByMenuId, Long seq,
			String prompt, Date startDate, Date endDate, Integer createdBy,
			Date createdDate, Integer updatedBy, Date updatedDate) {
		this.id = id;
		this.osiFunctions = osiFunctions;
		this.osiMenusBySubMenuId = osiMenusBySubMenuId;
		this.osiMenusByMenuId = osiMenusByMenuId;
		this.seq = seq;
		this.prompt = prompt;
		this.startDate = startDate;
		this.endDate = endDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "func_id")
	public OsiFunctions getOsiFunctions() {
		return this.osiFunctions;
	}

	public void setOsiFunctions(OsiFunctions osiFunctions) {
		this.osiFunctions = osiFunctions;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_menu_id")
	public OsiMenus getOsiMenusBySubMenuId() {
		return this.osiMenusBySubMenuId;
	}

	public void setOsiMenusBySubMenuId(OsiMenus osiMenusBySubMenuId) {
		this.osiMenusBySubMenuId = osiMenusBySubMenuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public OsiMenus getOsiMenusByMenuId() {
		return this.osiMenusByMenuId;
	}

	public void setOsiMenusByMenuId(OsiMenus osiMenusByMenuId) {
		this.osiMenusByMenuId = osiMenusByMenuId;
	}

	@Column(name = "seq", nullable = false)
	public Long getSeq() {
		return this.seq;
	}

	public void setSeq(Long seq) {
		this.seq = seq;
	}

	@Column(name = "prompt", nullable = false, length = 100)
	public String getPrompt() {
		return this.prompt;
	}

	public void setPrompt(String prompt) {
		this.prompt = prompt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
