package com.osi.urm.domain;

// Generated Nov 30, 2016 8:27:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiOperations generated by hbm2java
 */
@Entity
@Table(name = "osi_operations")
public class OsiOperations implements java.io.Serializable {

	private Integer id;
	private OsiFunctions osiFunctions;
	private String opType;
	private String opValue;
	private String parameters;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;

	public OsiOperations() {
	}

	public OsiOperations(String opType) {
		this.opType = opType;
	}

	public OsiOperations(OsiFunctions osiFunctions, String opType,
			String opValue, String parameters, Integer createdBy,
			Date createdDate, Integer updatedBy, Date updatedDate) {
		this.osiFunctions = osiFunctions;
		this.opType = opType;
		this.opValue = opValue;
		this.parameters = parameters;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "func_id")
	public OsiFunctions getOsiFunctions() {
		return this.osiFunctions;
	}

	public void setOsiFunctions(OsiFunctions osiFunctions) {
		this.osiFunctions = osiFunctions;
	}

	@Column(name = "op_type", nullable = false, length = 100)
	public String getOpType() {
		return this.opType;
	}

	public void setOpType(String opType) {
		this.opType = opType;
	}

	@Column(name = "op_value", length = 65535)
	public String getOpValue() {
		return this.opValue;
	}

	public void setOpValue(String opValue) {
		this.opValue = opValue;
	}

	@Column(name = "parameters", length = 1000)
	public String getParameters() {
		return this.parameters;
	}

	public void setParameters(String parameters) {
		this.parameters = parameters;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

}
