package com.osi.urm.domain;

// Generated Nov 28, 2016 7:51:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.osi.urm.service.dto.OsiMenusDTO;

/**
 * OsiResponsibilities generated by hbm2java
 */
@Entity
@Table(name = "osi_responsibilities")
public class OsiResponsibilities implements java.io.Serializable {
	
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	private OsiMenus osiMenus;
	private String respName;
	private String description;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Set<OsiRespUser> osiRespUsers = new HashSet<OsiRespUser>(0);
	private Date startDate;
	private Date endDate;

	public OsiResponsibilities() {
	}
	

	public OsiResponsibilities(int id, Date startDate, Date endDate) {
		this.id = id;
		this.startDate = startDate;
		this.endDate = endDate;
	} 
	public OsiResponsibilities(Integer id, OsiMenus osiMenus, String respName) {
		this.id = id;
		this.osiMenus = osiMenus;
		this.respName = respName;
	}

	public OsiResponsibilities(Integer id, OsiMenus osiMenus, String respName,
			String description, Integer createdBy, Date createdDate,
			Integer updatedBy, Date updatedDate, Set<OsiRespUser> osiRespUsers,Date startDate,
			Date endDate) {
		this.id = id;
		this.osiMenus = osiMenus;
		this.respName = respName;
		this.description = description;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.osiRespUsers = osiRespUsers;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public OsiMenus getOsiMenus() {
		return this.osiMenus;
	}

	public void setOsiMenus(OsiMenus osiMenus) {
		this.osiMenus = osiMenus;
	}

	@Column(name = "resp_name", nullable = false, length = 1000)
	public String getRespName() {
		return this.respName;
	}

	public void setRespName(String respName) {
		this.respName = respName;
	}

	@Column(name = "description", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiResponsibilities")
	public Set<OsiRespUser> getOsiRespUsers() {
		return this.osiRespUsers;
	}

	public void setOsiRespUsers(Set<OsiRespUser> osiRespUsers) {
		this.osiRespUsers = osiRespUsers;
	}

	public static void delete(Long id2) {
		// TODO Auto-generated method stub
		
	}
	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 0)
	public Date getEndDate() {
		return this.endDate;
	}
	
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	
}
