package com.osi.urm.domain;
// Generated Nov 28, 2016 7:51:32 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OsiUser generated by hbm2java
 */
@Entity
@Table(name = "osi_user")
public class OsiUser implements java.io.Serializable {

	private int id;
	private String userName;
	private String password;
	private String firstName;
	private String lastName;
	private String emailId;
	private String mobileNumber;
	private Date startDate;
	private String fullName;
	private Date endDate;
	private Integer createdBy;
	private Date createdDate;
	private Integer updatedBy;
	private Date updatedDate;
	private Set<OsiUserLogins> osiUserLoginses = new HashSet<OsiUserLogins>(0);
	private Set<OsiUserFuncExcl> osiUserFuncExcls = new HashSet<OsiUserFuncExcl>(
			0);
	private Set<OsiAttachments> osiAttachmentses = new HashSet<OsiAttachments>(
			0);
	private Set<OsiRespUser> osiRespUsers = new HashSet<OsiRespUser>(0);
	private Set<OsiUserOperationExcl> osiUserOperationExcls = new HashSet<OsiUserOperationExcl>(
			0);

	public OsiUser() {
	}

	public OsiUser(int id, String userName, String password, String emailId,
			String mobileNumber, Date startDate, Date endDate) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.emailId = emailId;
		this.mobileNumber = mobileNumber;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public OsiUser(int id, String userName, String password, String firstName,
			String lastName, String emailId, String mobileNumber,
			Date startDate, String fullName, Date endDate, Integer createdBy,
			Date createdDate, Integer updatedBy, Date updatedDate,
			Set<OsiUserLogins> osiUserLoginses,
			Set<OsiUserFuncExcl> osiUserFuncExcls,
			Set<OsiAttachments> osiAttachmentses,
			Set<OsiRespUser> osiRespUsers,
			Set<OsiUserOperationExcl> osiUserOperationExcls) {
		this.id = id;
		this.userName = userName;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailId = emailId;
		this.mobileNumber = mobileNumber;
		this.startDate = startDate;
		this.fullName = fullName;
		this.endDate = endDate;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.osiUserLoginses = osiUserLoginses;
		this.osiUserFuncExcls = osiUserFuncExcls;
		this.osiAttachmentses = osiAttachmentses;
		this.osiRespUsers = osiRespUsers;
		this.osiUserOperationExcls = osiUserOperationExcls;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "user_name", nullable = false, length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email_id", nullable = false, length = 50)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "mobile_number", nullable = false, length = 11)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 0)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Column(name = "full_name", length = 100)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 0)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 0)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", length = 0)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiUser")
	public Set<OsiUserLogins> getOsiUserLoginses() {
		return this.osiUserLoginses;
	}

	public void setOsiUserLoginses(Set<OsiUserLogins> osiUserLoginses) {
		this.osiUserLoginses = osiUserLoginses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiUser")
	public Set<OsiUserFuncExcl> getOsiUserFuncExcls() {
		return this.osiUserFuncExcls;
	}

	public void setOsiUserFuncExcls(Set<OsiUserFuncExcl> osiUserFuncExcls) {
		this.osiUserFuncExcls = osiUserFuncExcls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiUser")
	public Set<OsiAttachments> getOsiAttachmentses() {
		return this.osiAttachmentses;
	}

	public void setOsiAttachmentses(Set<OsiAttachments> osiAttachmentses) {
		this.osiAttachmentses = osiAttachmentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiUser")
	public Set<OsiRespUser> getOsiRespUsers() {
		return this.osiRespUsers;
	}

	public void setOsiRespUsers(Set<OsiRespUser> osiRespUsers) {
		this.osiRespUsers = osiRespUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "osiUser")
	public Set<OsiUserOperationExcl> getOsiUserOperationExcls() {
		return this.osiUserOperationExcls;
	}

	public void setOsiUserOperationExcls(
			Set<OsiUserOperationExcl> osiUserOperationExcls) {
		this.osiUserOperationExcls = osiUserOperationExcls;
	}

}
